[package]
name = "val_electron_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4.0"
dioxus-web = "0.4.0"
minecraft-data-rs = "0.7.2"
enum_dispatch = "0.3.12"
log = "0.4.20"
dioxus-logger = "0.4.1"